Name: prod
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

job:
  Deploy:
    runon: ubantu-latest
    steps:
      - uses: actions/checkout@v4
      - name: intall vercal cli
        run: npm i vercel -g
      - name: Pull evn information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Artifcats
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}